# Generated by Django 4.2 on 2023-05-04 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 4, 18, 54, 56, 725974, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
